# .air.toml
root = "."
tmp_dir = "tmp"
[build]
bin = "./tmp/main" 
cmd = "go build -o ./tmp/main cmd/app/main.go" 
delay = 5000 # ms
exclude_dir = ["assets", "tmp", "vendor"] 
exclude_regex = ["_test\\.go"] 
include_ext = ["go", "tpl", "tmpl", "html"]
