version: "3"

services:
  gomeet-back:
    build: .
    container_name: gomeet-back
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
    restart: always
  gomeet-front:
    build: frontend
    container_name: gomeet-front
    volumes:
      - /home/bun/app
    ports:
      - "3000:3000"
  arangodb:
    image: arangodb
    container_name: arangodb
    volumes:
      - ./.docker/arangodb:/var/lib/arangodb3
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD
